syntax = "proto3";

package vertice.exercise.v1;

import "google/protobuf/empty.proto";

option java_package = "com.vertice.api.generated.grpc.exercise.v1";
option java_multiple_files = true;

service ExerciseService {
  rpc ListMuscleGroups(ListMuscleGroupsRequest) returns (ListMuscleGroupsResponse);
  rpc ListExercises(ListExercisesRequest) returns (ListExercisesResponse);
  rpc GetExercise(GetExerciseRequest) returns (ExerciseResponse);
  rpc CreateExercise(ExerciseRequest) returns (ExerciseResponse);
  rpc UpdateExercise(UpdateExerciseRequest) returns (ExerciseResponse);
  rpc DeleteExercise(DeleteExerciseRequest) returns (google.protobuf.Empty);
}

message MuscleGroupResponse {
  int64 id = 1;
  string name = 2;
}

message ListMuscleGroupsRequest {
}

message ListMuscleGroupsResponse {
  repeated MuscleGroupResponse muscle_groups = 1;
}

message ExerciseResponse {
  reserved 5;
  reserved "muscle_group";
  int64 id = 1;
  string name = 2;
  string description = 3;
  string video_url = 4;
  repeated MuscleGroupResponse muscle_groups = 6;
  bool is_starter = 7;
}

message ExerciseRequest {
  reserved 4;
  reserved "muscle_group";
  string name = 1;
  string description = 2;
  string video_url = 3;
  repeated int64 muscle_group_ids = 5;
}

message ListExercisesRequest {
  int64 muscle_group_id = 1;
  string search = 2;
}

message ListExercisesResponse {
  repeated ExerciseResponse exercises = 1;
}

message GetExerciseRequest {
  int64 id = 1;
}

message UpdateExerciseRequest {
  int64 id = 1;
  ExerciseRequest exercise = 2;
}

message DeleteExerciseRequest {
  int64 id = 1;
}
